replicaCount: 1

autoscaling:
  enabled: false

podDisruptionBudget:
  enabled: false

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

env:
  ASPNETCORE_ENVIRONMENT: Staging

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: service-template.staging.example.com
      paths:
        - path: /
          pathType: Prefix
